### ISSUE TITLE
add bootstrap sticky footer

### ISSUE THREAD

**Issue by dmtrrk** [Mariam9/site-with-bootstrap#2]
- what is sticky footer?
- find out how to add sticky footer to a bootstrap site
- add sticky footer

**Comment by dmtrrk** [comment]
your footer makes my eyes bleed

**Comment by Mariam9** [comment]
this is tutorial's footer makes your eyes bleed :)

seriously, what's wrong with it?

**Comment by dmtrrk** [comment]
you don't know what is Sticky footer. you don't know what is Google

**Comment by Mariam9** [comment]
Who says that it is a _sticky_ footer? it's an usual footer. and i know what is google :)

http://www.cssstickyfooter.com/using-sticky-footer-code.html 
as i understood i should add some pieces of code at the bootstrap

**Comment by dmtrrk** [comment]
http://lmgtfy.com/?q=bootstrap+sticky+footer

**Comment by Mariam9** [comment]
what a funny joke, you are so funny guy. i'm laughing out loud

**Comment by Mariam9** [comment]
sticky footer uses when there' s a little content on the page. in this case footer pins to bottom of the browser's window. when there's enough of content, footer runs down.
