### ISSUE TITLE
Complex task

### ISSUE THREAD

**Issue by dmtrrk** [Mariam9/site-with-bootstrap#3]
- Main manu (navigation bar)
  - set Services menu active by default
  - After Downloads menu add Help menu item
- Sidebar nav menu
  - after Our services add a new menu item Help and make it active by default
  - Make Our friends nav menu header as What we are style (should not be a link)
- How do we market
  - add some favorite quote at any position
  - make 3-columns block instead of 2-column (Know Our Employees, Reach Us). Add any header and copy the text. The button should be of cancellation (error) type

**Comment by Mariam9** [comment]
> > make 3-columns block instead of 2-column (Know Our Employees, Reach Us). Add any header and copy the text. The button should be of cancellation (error) type

this is the footer area. It already has three columns - Our Clients, Know Our Employees and Reach Us.  Should I make 4 columns? Or I didn't understand you well?

**Comment by dmtrrk** [comment]
oops.. so add 4th column
